[project]
name = "snapfix"
version = "0.1.0"
description = ""
authors = [
    {name = "Paweł Komendera",email = "pawel.kamil.komendera@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyexiftool (>=0.5.6,<0.6.0)"
]

[tool.poetry]
packages = [{include = "snapfix", from = "src"}]

[tool.poetry.scripts]
snapfix = "snapfix.cli:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)"
]
